export enum ActionType {
  GET_MOVIE = "GET_MOVIE",
  GET_MOVIES = "GET_MOVIES",
  GET_SEARCHING_MOVIES = "GET_SEARCHING_MOVIES",
  GET_TEXT = "GET_TEXT",
  GET_SIMILAR_MOVIES = "GET_SIMILAR_MOVIES",
  GET_GENRE = "GET_GENRE",
  DELETE_GENRE = "DELETE_GENRE",
  GET_MOVIE_WITH_GENRE = "GET_MOVIE_WITH_GENRE",
  GET_GALLERY = "GET_GALLERY",
  GET_TOTAL_PAGES = "GET_TOTAL_RESULTS",
  GET_FAVORITE_LIST = "GET_FAVORITE_LIST",
  ADD_FAVORITE_LIST = "ADD_FAVORITE_LIST",
  DELETE_FAVORITE_LIST = "DELETE_FAVORITE_LIST",
  CLEAR_GENRES = "CLEAR_GENRES",
  TOGGLE_IS_FETCHING = "TOGGLE_IS_FETCHING"
}
